steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/ticket-service', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/ticket-service']
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      [
        'run', 'deploy', 'ticket-service',
        '--image', 'gcr.io/$PROJECT_ID/ticket-service',
        '--region', 'europe-north2',
        '--platform', 'managed',
        '--allow-unauthenticated'
      ]
images:
  - 'gcr.io/$PROJECT_ID/ticket-service'